#!/usr/bin/env python3
"""Build the Protocols and Pipelines pages of multee.org from the lab's protocol export.

    python tools/build_protocol_pages.py path/to/export      (a folder or a .zip)

The export comes from the lab's internal protocol log (Admin -> "Download public
export"): a protocols.json index plus the files it points to. This script writes

    protocols/index.html                 all protocols, by category
    protocols/<slug>/index.html          one protocol: text, figures, downloads, pipelines
    pipelines/index.html                 all pipelines
    pipelines/<slug>/index.html          one pipeline

and copies the downloads and images next to them. It never touches anything else
in the site. The header, menu and footer are taken from data.html each time, so
the generated pages follow any change to the rest of the site. Their styling
lives in assets/css/page-protocols.css (hand-maintained, like the other page-*.css).

The protocols/ and pipelines/ folders are REPLACED on every run: do not edit
files inside them by hand. Standard library only, so it runs anywhere Python 3.9+ does.
"""
import argparse
import html
import json
import re
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
TEMPLATE = "data.html"          # page whose header/menu/footer the generated pages reuse
NAV_CURRENT = "data.html"       # menu item highlighted on generated pages
MARKER = ".generated-by-build_protocol_pages"
GENERATED_NOTE = ("<!-- Generated by tools/build_protocol_pages.py from the lab's protocol log. "
                  "Do not edit: this file is replaced on every build. -->\n")
SECTION_HEAD = 'style="padding-block:var(--sp-8) var(--sp-6)"'
SECTION_BODY = 'style="padding-block:var(--sp-8)"'

esc = html.escape


# --- Entry point --------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("export", help="export folder, or the .zip downloaded from the protocol log")
    parser.add_argument("--site", default=str(SITE), help="website folder (default: this repository)")
    parser.add_argument("--allow-empty", action="store_true",
                        help="build even if the export has no published protocols (normally refused, "
                             "so a misconfigured export can't wipe the pages)")
    args = parser.parse_args(argv)

    site = Path(args.site).resolve()
    with tempfile.TemporaryDirectory() as tmp:
        export = Path(args.export).resolve()
        if export.suffix.lower() == ".zip":
            with zipfile.ZipFile(export) as zf:
                zf.extractall(tmp)
            export = Path(tmp)
        index_file = export / "protocols.json"
        if not index_file.is_file():
            sys.exit(f"No protocols.json in {args.export}. Is this a protocol export?")
        index = json.loads(index_file.read_text(encoding="utf-8"))
        if not any(c["protocols"] for c in index["categories"]) and not args.allow_empty:
            sys.exit("The export contains no published protocols; leaving the pages unchanged. "
                     "(Use --allow-empty if that is really intended.)")
        build(site, export, index)


def build(site, export, index):
    shell = Shell(site / TEMPLATE)
    protocols = {p["slug"]: dict(p, category=c) for c in index["categories"] for p in c["protocols"]}
    pipelines = {p["slug"]: p for p in index.get("pipelines", [])}

    out_protocols, out_pipelines = site / "protocols", site / "pipelines"
    for folder in (out_protocols, out_pipelines):
        _reset(folder)

    write(out_protocols / "index.html", shell.page(
        "Protocols", "Protocols used to run and study the MuLTEE, written and maintained by the lab.",
        protocols_index(index), depth=1))
    for slug, p in protocols.items():
        _copy_files(export, site, [p["files"].get("original"), p["files"].get("pdf")]
                    + [x for ph in p.get("photos", []) for x in (ph["image"], ph["thumbnail"])])
        fragment = ""
        if p["files"].get("html"):
            fragment = (export / p["files"]["html"]).read_text(encoding="utf-8")
        write(out_protocols / slug / "index.html", shell.page(
            p["title"], p["purpose"] or f"{p['title']}: a MuLTEE protocol.",
            protocol_page(p, fragment, pipelines), depth=2))

    write(out_pipelines / "index.html", shell.page(
        "Analysis pipelines", "Analysis code used with the MuLTEE protocols.",
        pipelines_index(pipelines, protocols), depth=1))
    for slug, pl in pipelines.items():
        _copy_files(export, site, [pl.get("zip")])
        write(out_pipelines / slug / "index.html", shell.page(
            pl["title"], pl["description"] or f"{pl['title']}: a MuLTEE analysis pipeline.",
            pipeline_page(pl, protocols, site), depth=2))

    print(f"Built {len(protocols)} protocol page(s) and {len(pipelines)} pipeline page(s) in {site}")


def _reset(folder):
    """Empty a generated folder, refusing to touch one this script didn't create."""
    if folder.exists():
        if not (folder / MARKER).exists():
            sys.exit(f"{folder} exists but wasn't created by this script; not overwriting it.")
        shutil.rmtree(folder)
    folder.mkdir(parents=True)
    (folder / MARKER).write_text("Generated by tools/build_protocol_pages.py; replaced on every build.\n")


def _copy_files(export, site, rel_paths):
    for rel in filter(None, rel_paths):
        dest = site / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(export / rel, dest)


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


# --- The site's own header, menu and footer -----------------------------------

class Shell:
    """Everything outside <main> in the template page, adapted for generated pages."""

    def __init__(self, template_path):
        text = template_path.read_text(encoding="utf-8")
        start, end = text.index('<main id="main">'), text.index("</main>") + len("</main>")
        before, self.after = text[:start], text[end:]
        # Swap the template's page-specific stylesheet(s) for ours.
        before = re.sub(r'\n?<link rel="stylesheet" href="assets/css/page-[^"]+\.css">', "", before)
        before = before.replace('<link rel="stylesheet" href="assets/css/site.css">',
                                '<link rel="stylesheet" href="assets/css/site.css">\n'
                                '<link rel="stylesheet" href="assets/css/page-protocols.css">')
        before = before.replace(' aria-current="page"', "")
        before = before.replace(f'<a href="{NAV_CURRENT}">', f'<a href="{NAV_CURRENT}" aria-current="page">')
        self.before = before

    def page(self, title, description, main_html, depth):
        before = re.sub(r"<title>.*?</title>", lambda m: f"<title>{esc(title)} | MuLTEE</title>",
                        self.before, flags=re.S)
        before = re.sub(r'(<meta name="description" content=")[^"]*(")',
                        lambda m: m.group(1) + esc(_one_line(description), quote=True) + m.group(2), before)
        before = before.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + GENERATED_NOTE.rstrip(), 1)
        page = before + '<main id="main">\n' + main_html + "\n</main>" + self.after
        return _relink(page, "../" * depth)


_LINK = re.compile(r'(\s(?:href|src)=")([^"]*)(")')


def _relink(page, prefix):
    """Make site-relative and root-absolute links work from a page `depth` folders down
    (and from a local copy opened without a web server)."""
    def fix(m):
        url = m.group(2)
        if not url or url.startswith(("#", "//")) or re.match(r"^[a-zA-Z][\w+.-]*:", url):
            return m.group(0)
        return m.group(1) + prefix + url.lstrip("/") + m.group(3)
    return _LINK.sub(fix, page)


def _one_line(text):
    text = " ".join((text or "").split())
    return text if len(text) <= 300 else text[:297].rsplit(" ", 1)[0] + "…"


# --- Pages --------------------------------------------------------------------
# Links are written relative to the site root ("protocols/x/"); _relink adjusts them.

def protocols_index(index):
    cats = [c for c in index["categories"] if c["protocols"]]
    total = sum(len(c["protocols"]) for c in cats)
    doors = "\n".join(
        f'''      <a class="door" href="#{esc(c["slug"])}">
        <span class="count">{_count(len(c["protocols"]), "protocol")}</span>
        <h3>{esc(c["name"])}</h3>
        {f'<p>{esc(c["description"])}</p>' if c["description"] else ""}
      </a>''' for c in cats)
    sections = "\n\n  <hr class=\"rule\">\n\n".join(
        f'''  <div class="page">
    <section class="section" id="{esc(c["slug"])}" {SECTION_BODY}>
      <div class="section-head">
        <p class="eyebrow">{_count(len(c["protocols"]), "protocol")}</p>
        <h2>{esc(c["name"])}</h2>
        {f'<p class="dim" style="margin-top:var(--sp-3)">{esc(c["description"])}</p>' if c["description"] else ""}
      </div>
      <ul class="pubs">
{"".join(_protocol_item(p) for p in c["protocols"])}      </ul>
    </section>
  </div>''' for c in cats)
    return f'''  <div class="page">
    <section class="section" {SECTION_HEAD}>
      <p class="eyebrow"><a href="data.html#resources">Data &amp; Strains</a> / Protocols</p>
      <h1 class="display">Protocols</h1>
      <p class="lede">How the MuLTEE is run and measured, from daily settling selection to
        phenotyping. {_count(total, "protocol")}, written and maintained by the lab and updated as
        methods change.</p>
      <p class="protocol-actions"><a class="btn btn-ghost" href="pipelines/">Analysis pipelines</a></p>
    </section>
  </div>

  <div class="page">
    <section class="section wide" style="padding-block:0 var(--sp-8)">
      <nav class="doors" aria-label="Protocol categories">
{doors}
      </nav>
    </section>
  </div>

  <hr class="rule">

{sections}
  <div class="page">
    <section class="section" {SECTION_BODY}>
      <p class="plate-caption">{_updated_note(index)}</p>
    </section>
  </div>'''


def _protocol_item(p):
    meta = [f"By {esc(p['author'])}", f"Version {p['version']}", f"Updated {esc(p['last_updated'])}"]
    if p.get("photos"):
        meta.append(_count(len(p["photos"]), "figure"))
    if p.get("pipelines"):
        meta.append(_count(len(p["pipelines"]), "pipeline"))
    return f'''        <li>
          <h3 class="pub-title"><a href="protocols/{esc(p["slug"])}/">{esc(p["title"])}</a></h3>
          <p class="pub-meta">{"".join(f"<span>{m}</span>" for m in meta)}</p>
          {f'<p class="finding-text">{esc(p["purpose"])}</p>' if p["purpose"] else ""}
        </li>
'''


def protocol_page(p, fragment, pipelines):
    cat = p["category"]
    files = p["files"]
    actions = []
    if files.get("original"):
        ext = files["original"].rsplit(".", 1)[-1]
        actions.append(f'<a class="btn" href="{esc(files["original"])}" download>Download (.{esc(ext)})</a>')
    if files.get("pdf"):
        actions.append(f'<a class="btn btn-ghost" href="{esc(files["pdf"])}">PDF</a>')
    meta = [f'<span class="venue">{esc(cat["name"])}</span>', f"<span>By {esc(p['author'])}</span>",
            f"<span>Version {p['version']} · updated {esc(p['last_updated'])}</span>"]

    body = _prepare_fragment(fragment, p["title"]) if fragment else (
        '<p class="dim">This protocol is available as a download above.</p>')
    parts = [f'''  <div class="page">
    <section class="section" {SECTION_HEAD}>
      <p class="eyebrow"><a href="protocols/">Protocols</a> / <a href="protocols/#{esc(cat["slug"])}">{esc(cat["name"])}</a></p>
      <h1 class="display protocol-title">{esc(p["title"])}</h1>
      <p class="pub-meta protocol-meta">{"".join(meta)}</p>
      {f'<p class="lede">{esc(p["purpose"])}</p>' if p["purpose"] else ""}
      {f'<p class="protocol-actions">{" ".join(actions)}</p>' if actions else ""}
    </section>
  </div>

  <hr class="rule">

  <div class="page">
    <article class="section prose protocol-body" {SECTION_BODY}>
{body}
    </article>
  </div>''']

    if p.get("photos"):
        parts.append(f'''  <div class="page">
    <section class="section wide" id="figures" {SECTION_BODY}>
      <div class="section-head">
        <p class="eyebrow">{_count(len(p["photos"]), "figure")}</p>
        <h2>Figures</h2>
      </div>
      <div class="protocol-figures">
{"".join(_figure(ph, p["title"]) for ph in p["photos"])}      </div>
    </section>
  </div>''')

    used = [pipelines[s] for s in p.get("pipelines", []) if s in pipelines]
    if used:
        parts.append(f'''  <div class="page">
    <section class="section" id="pipelines" {SECTION_BODY}>
      <div class="section-head">
        <p class="eyebrow">Analysis</p>
        <h2>Analysis pipelines</h2>
      </div>
      <ul class="pubs">
{"".join(_pipeline_item(pl) for pl in used)}      </ul>
    </section>
  </div>''')
    return "\n\n  <hr class=\"rule\">\n\n".join(parts)


def _prepare_fragment(fragment, title):
    """Fit converted protocol text under the page's own <h1>."""
    # A first heading that just repeats the title is dropped (its anchor is kept).
    m = re.match(r'\s*(?:<p>.*?</p>\s*)?<h([1-6])(?: id="([^"]*)")?[^>]*>(.*?)</h\1>', fragment, re.S)
    if m and _plain(m.group(3)).casefold() == _plain(title).casefold():
        anchor = f'<span id="{m.group(2)}"></span>' if m.group(2) else ""
        fragment = fragment[:m.start(1) - 2] + anchor + fragment[m.end():]
    # The page has the only <h1>; protocol headings start at <h2>.
    if re.search(r"<h1[\s>]", fragment):
        fragment = re.sub(r"<(/?)h([1-5])([\s>])", lambda h: f"<{h.group(1)}h{int(h.group(2)) + 1}{h.group(3)}",
                          fragment)
    # Wide tables scroll sideways instead of breaking the layout on phones.
    fragment = re.sub(r"<table", '<div class="scroll-x"><table', fragment)
    return fragment.replace("</table>", "</table></div>")


def _plain(markup):
    return " ".join(html.unescape(re.sub(r"<[^>]+>", "", markup)).split())


def _figure(ph, protocol_title):
    n = ph["figure"]
    title = ph.get("title") or ""
    paragraphs = [para for para in (ph.get("legend") or "").split("\n\n") if para.strip()]
    legend = "".join(f"<p>{esc(para).replace(chr(10), '<br>')}</p>" for para in paragraphs)
    alt = f"Figure {n} of {protocol_title}" + (f": {title}" if title else "")
    return f'''        <div class="protocol-figure" id="figure-{n}">
          <figure class="plate">
            <a class="plate-figure figure-media" href="{esc(ph["image"])}" title="Open full size">
              <img src="{esc(ph["image"])}" width="{ph["width"]}" height="{ph["height"]}" loading="lazy" alt="{esc(alt, quote=True)}">
            </a>
            <figcaption class="plate-label"><p class="plate-num">Figure {n}</p></figcaption>
          </figure>
          <div class="plate-caption figure-legend">
            <p><strong>Figure {n}.</strong> {esc(title)}</p>
            {legend}
          </div>
        </div>
'''


def _pipeline_item(pl):
    meta = [f"By {esc(pl['author'])}", f"Updated {esc(pl['last_updated'])}"]
    meta.append(" + ".join(x for x in ("Link" if pl.get("url") else "", "Zip" if pl.get("zip") else "") if x))
    return f'''        <li>
          <h3 class="pub-title"><a href="pipelines/{esc(pl["slug"])}/">{esc(pl["title"])}</a></h3>
          <p class="pub-meta">{"".join(f"<span>{m}</span>" for m in meta)}</p>
          {f'<p class="finding-text">{esc(pl["description"])}</p>' if pl["description"] else ""}
        </li>
'''


def pipelines_index(pipelines, protocols):
    items = "".join(_pipeline_item(pl) for pl in pipelines.values())
    return f'''  <div class="page">
    <section class="section" {SECTION_HEAD}>
      <p class="eyebrow"><a href="data.html#resources">Data &amp; Strains</a> / Pipelines</p>
      <h1 class="display">Analysis pipelines</h1>
      <p class="lede">Code the lab uses to analyse MuLTEE data, with the protocols each one goes with.</p>
      <p class="protocol-actions"><a class="btn btn-ghost" href="protocols/">Protocols</a></p>
    </section>
  </div>

  <hr class="rule">

  <div class="page">
    <section class="section" {SECTION_BODY}>
      {f'<ul class="pubs">{items}</ul>' if items else '<p class="dim">No pipelines are posted yet.</p>'}
      <p class="plate-caption" style="margin-top:var(--sp-6)">Other code is available on request:
        see <a href="data.html#contact">who to write to</a>.</p>
    </section>
  </div>'''


def pipeline_page(pl, protocols, site):
    actions = []
    if pl.get("url"):
        actions.append(f'<a class="btn" href="{esc(pl["url"], quote=True)}" rel="noopener">Get the code</a>')
    contents = ""
    if pl.get("zip"):
        zpath = site / pl["zip"]
        size = _filesize(zpath.stat().st_size) if zpath.is_file() else ""
        cls = "btn btn-ghost" if actions else "btn"
        actions.append(f'<a class="{cls}" href="{esc(pl["zip"])}" download>Download (.zip{", " + size if size else ""})</a>')
        contents = _zip_contents(zpath)
    used = [protocols[s] for s in pl.get("protocols", []) if s in protocols]
    used_html = "".join(f'''        <li>
          <h3 class="pub-title"><a href="protocols/{esc(p["slug"])}/">{esc(p["title"])}</a></h3>
          <p class="pub-meta"><span class="venue">{esc(p["category"]["name"])}</span><span>By {esc(p["author"])}</span></p>
        </li>
''' for p in used)
    return f'''  <div class="page">
    <section class="section" {SECTION_HEAD}>
      <p class="eyebrow"><a href="pipelines/">Analysis pipelines</a></p>
      <h1 class="display protocol-title">{esc(pl["title"])}</h1>
      <p class="pub-meta protocol-meta"><span>By {esc(pl["author"])}</span><span>Updated {esc(pl["last_updated"])}</span></p>
      {f'<p class="lede">{esc(pl["description"])}</p>' if pl["description"] else ""}
      {f'<p class="protocol-actions">{" ".join(actions)}</p>' if actions else ""}
      {f'<p class="plate-caption">{esc(pl["url"])}</p>' if pl.get("url") else ""}
    </section>
  </div>

  <hr class="rule">

  <div class="page">
    <section class="section" {SECTION_BODY}>
      <div class="section-head">
        <p class="eyebrow">Used with</p>
        <h2>Protocols that use this pipeline</h2>
      </div>
      {f'<ul class="pubs">{used_html}</ul>' if used_html else '<p class="dim">Not linked to a posted protocol yet.</p>'}
      {contents}
    </section>
  </div>'''


def _zip_contents(path, limit=60):
    if not path.is_file():
        return ""
    with zipfile.ZipFile(path) as zf:
        entries = [(i.filename, i.file_size) for i in zf.infolist() if not i.is_dir()]
    rows = "".join(f"<li><span>{esc(name)}</span><span class=\"num\">{_filesize(size)}</span></li>"
                   for name, size in entries[:limit])
    more = f'<li class="dim">…and {len(entries) - limit} more</li>' if len(entries) > limit else ""
    return f'''<details class="zip-contents">
        <summary class="label">What's in the zip ({_count(len(entries), "file")})</summary>
        <ul>{rows}{more}</ul>
      </details>'''


def _updated_note(index):
    # The date of the newest change, not of the build: an unchanged export must
    # produce byte-identical pages so the nightly update has nothing to commit.
    dates = [p["last_updated"] for c in index["categories"] for p in c["protocols"]]
    latest = f" Last change {esc(max(dates))}." if dates else ""
    return (f"Maintained in the lab's protocol log.{latest} "
            "Questions about a protocol: see <a href=\"data.html#contact\">who to write to</a>.")


def _count(n, word):
    return f"{n} {word}{'' if n == 1 else 's'}"


def _filesize(n):
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.0f} KB"
    return f"{n / (1024 * 1024):.1f} MB"


if __name__ == "__main__":
    main()
